spring:
  profiles:
    active: dev

druid:
  driver-class-name: oracle.jdbc.OracleDriver
  url: jdbc:oracle:thin:@114.112.254.10:1521:hkdb06
  username: damon
  password: damon000
  initialSize: 5
  minIdle: 5
  maxWait: 60000
  maxActive: 20
  minEvictableIdleTimeMillis: 300000

mybatis:
  type-aliases-package: com.gmh.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
